### ISSUE TITLE
occurrence records

### ISSUE THREAD

**Issue by swfbtucs** [bmaitner/RBIEN#1]
Is there an argument for this or another function that can get me the collector/observer's name (and collection number) for a range/specific record? Or can I modify the code? Or can I at least get a printout of what fields are returned by running a function?

**Comment by bmaitner** [comment]
I can add an option to return the collection number, observer's name, identifier's name and any similar metadata.  Should have it later today.  I'll add this to all of the occurrence data.

Since the ranges are produced from a set of occurrence data, there isn't a specific observer's name associated with them, but Cory Merow (@cmerow), Naia Morueta-Holme (@naiamh) and Brian McGill did most of the modelling with Nathan Casler (@npcasler) helping out on the computational aspects.

As for a printout of what fields are returned by running a function, this is an excellent idea.  I'll create a new issue for this.  In the meantime, the easiest way to see what will be returned by a query without waiting for the complete set of data to download is to add the argument `limit = 1` to your query, for example,

```{r}
BIEN_occurrence_species(species = "Xanthium strumarium", limit = 1)
```

This will only return one record, so it is currently the fastest way to answer this question, but I'll fix that soon.  The data dictionary at [http://bien.nceas.ucsb.edu/bien/tools/rbien/data-dictionary/](url) also provides a way of figuring out what types of data are returned.

**Comment by swfbtucs** [comment]
Thank you Brian! This would help out quite a bit. I am looking forward to it.

Frank

**Comment by bmaitner** [comment]
Alright, if you install from the Github version, the BIEN_occurrence_... functions have a new argument called `collection.info`, set this to TRUE for some additional metadata and let me know what you think.

**Comment by swfbtucs** [comment]
Thanks!

FYI, I’m working with www.madreandiscovery.org<http://www.madreandiscovery.org> to develop a QGIS database of our collecting data and to develop lists of species already collected in our study area. I have noted that I can set up and run R scripts from within QGIS. So we’ll see where this goes!

Frank

**Comment by bmaitner** [comment]
Hi Frank,

Sounds like a cool project!  Feel free to shoot me an email (bmaitner@gmail.com) if you have any more ideas about how the BIEN data can be useful for your project.
